[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/map"
  to = "/map/index.html"
  status = 200

[[redirects]]
  from = "/map/"
  to = "/map/index.html"
  status = 200
